'use client'

import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, Bell, ChevronDown, CreditCard, LayoutDashboard, Menu, Plus, Search, Settings2, Sparkles, Target, WalletCards, X } from 'lucide-react'

const nav = [{ label: 'Vue d’ensemble', icon: LayoutDashboard }, { label: 'Transactions', icon: ArrowDownLeft }, { label: 'Mes poches', icon: WalletCards }, { label: 'Budgets', icon: Target }, { label: 'Analyses', icon: Sparkles }]
const transactions = [{ name: 'Salaire — Août', category: 'Revenus', date: 'Aujourd’hui, 09:42', amount: '+ 450 000 FCFA', tone: 'income', icon: ArrowDownLeft }, { name: 'Carrefour Market', category: 'Alimentation', date: 'Hier, 18:20', amount: '− 28 450 FCFA', tone: 'expense', icon: ArrowUpRight }, { name: 'Abonnement Netflix', category: 'Divertissement', date: '22 août, 08:12', amount: '− 6 500 FCFA', tone: 'expense', icon: CreditCard }, { name: 'Transfert vers Épargne', category: 'Épargne', date: '20 août, 14:05', amount: '− 50 000 FCFA', tone: 'transfer', icon: Target }]

export default function Home() {
  const [active, setActive] = useState('Vue d’ensemble'); const [mobileOpen, setMobileOpen] = useState(false); const [hidden, setHidden] = useState(false)
  return <main className="min-h-screen bg-paper">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-line bg-surface px-6 py-7 transition-transform md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-12 flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-ink text-sm font-bold text-white">M</div><span className="font-display text-xl font-bold tracking-tight">mes poches</span></div><button className="md:hidden" onClick={() => setMobileOpen(false)} aria-label="Fermer"><X /></button></div>
      <nav className="flex flex-col gap-2">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition ${active === label ? 'bg-mint text-jade' : 'text-muted hover:bg-paper hover:text-ink'}`}><Icon size={18} />{label}{label === 'Analyses' && <span className="ml-auto rounded-full bg-ink px-2 py-0.5 text-[10px] text-white">PRO</span>}</button>)}</nav>
      <div className="mt-auto rounded-2xl bg-ink p-4 text-white"><Sparkles size={19} className="mb-5 text-[#dff3ea]" /><p className="mb-2 text-sm font-semibold">Passez au niveau supérieur</p><p className="mb-4 text-xs leading-5 text-white/60">Des analyses qui vous aident à décider, pas seulement à compter.</p><button className="w-full rounded-lg bg-white px-3 py-2 text-xs font-bold text-ink">Découvrir Premium</button></div>
      <button className="mt-6 flex items-center gap-3 border-t border-line pt-5 text-sm font-semibold text-muted"><Settings2 size={18} />Paramètres</button>
    </aside>
    <section className="md:pl-64"><header className="flex items-center justify-between border-b border-line bg-surface/80 px-5 py-5 backdrop-blur md:px-10"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(true)} className="md:hidden" aria-label="Ouvrir le menu"><Menu /></button><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted">Mercredi 27 août 2026</p><h1 className="mt-1 font-display text-2xl font-bold">Bonjour, Charles<span className="text-jade">.</span></h1></div></div><div className="flex items-center gap-3"><button className="hidden rounded-xl border border-line bg-paper p-2.5 text-muted sm:block" aria-label="Rechercher"><Search size={18} /></button><button className="rounded-xl border border-line bg-paper p-2.5 text-muted" aria-label="Notifications"><Bell size={18} /></button><div className="flex size-9 items-center justify-center rounded-full bg-ink text-xs font-bold text-white">CL</div></div></header>
      <div className="mx-auto max-w-[1400px] px-5 py-7 md:px-10 md:py-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold text-jade">Votre situation financière</p><h2 className="font-display text-4xl font-bold tracking-tight md:text-5xl">Vue d’ensemble</h2></div><button className="flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white transition hover:opacity-90"><Plus size={17} />Nouvelle transaction</button></div>
        <div className="grid gap-4 lg:grid-cols-[1.45fr_1fr_1fr]"><div className="rounded-2xl bg-ink p-6 text-white md:p-7"><div className="flex items-start justify-between"><div><p className="text-sm text-white/60">Solde total</p><p className="mt-3 font-display text-4xl font-bold md:text-5xl">{hidden ? '••••••' : '1 284 750'} <span className="text-base font-sans font-normal text-white/60">FCFA</span></p></div><button onClick={() => setHidden(!hidden)} className="rounded-lg bg-white/10 px-3 py-1.5 text-xs text-white/70">{hidden ? 'Afficher' : 'Masquer'}</button></div><div className="mt-8 flex items-center gap-2 text-sm"><span className="rounded-full bg-[#dff3ea] px-2 py-1 font-bold text-jade">+12,4 %</span><span className="text-white/50">vs. mois dernier</span></div></div><StatCard label="Revenus ce mois" value="450 000" delta="+ 8,2 %" positive icon={ArrowDownLeft} /><StatCard label="Dépenses ce mois" value="186 250" delta="− 4,1 %" positive icon={ArrowUpRight} /></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-2xl border border-line bg-surface p-6 md:p-7"><div className="flex items-center justify-between"><div><h3 className="font-display text-xl font-bold">Flux de trésorerie</h3><p className="mt-1 text-sm text-muted">Vos mouvements sur les 6 derniers mois</p></div><button className="flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-xs font-bold">Août <ChevronDown size={14} /></button></div><div className="mt-8 flex h-48 items-end gap-3 sm:gap-7"><div className="flex h-full flex-1 flex-col justify-between text-[10px] text-muted"><span>600k</span><span>400k</span><span>200k</span><span>0</span></div>{[48, 62, 42, 76, 58, 90].map((height, i) => <div key={i} className="flex h-full flex-1 flex-col justify-end gap-3"><div className="flex items-end justify-center gap-1.5"><div className="w-2 rounded-t bg-[#b9e3d3] sm:w-3" style={{ height: `${height * .7}%` }} /><div className="w-2 rounded-t bg-jade sm:w-3" style={{ height: `${height}%` }} /></div><span className="text-center text-[10px] text-muted">{['Mars', 'Avr', 'Mai', 'Juin', 'Juil', 'Août'][i]}</span></div>)}</div><div className="mt-5 flex gap-5 text-xs text-muted"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-jade" />Revenus</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#b9e3d3]" />Dépenses</span></div></section>
        <section className="rounded-2xl border border-line bg-surface p-6 md:p-7"><div className="flex items-center justify-between"><div><h3 className="font-display text-xl font-bold">Répartition</h3><p className="mt-1 text-sm text-muted">Dépenses par catégorie</p></div><button className="text-xs font-bold text-jade">Voir tout</button></div><div className="mx-auto my-7 flex size-40 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#087f68 0 38%, #64b99b 38% 64%, #b9e3d3 64% 82%, #e5ebe7 82% 100%)' }}><div className="flex size-24 flex-col items-center justify-center rounded-full bg-surface"><span className="font-display text-xl font-bold">186k</span><span className="text-[10px] text-muted">FCFA</span></div></div><div className="flex flex-col gap-3 text-xs">{[['Alimentation','38%','bg-jade'],['Transport','26%','bg-[#64b99b]'],['Maison','18%','bg-[#b9e3d3]']].map(([name, percent, color]) => <div key={name} className="flex items-center justify-between"><span className="flex items-center gap-2"><i className={`size-2 rounded-full ${color}`} />{name}</span><b>{percent}</b></div>)}</div></section></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-2xl border border-line bg-surface p-6 md:p-7"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-display text-xl font-bold">Activité récente</h3><p className="mt-1 text-sm text-muted">Vos dernières transactions</p></div><button className="text-xs font-bold text-jade">Toutes les transactions</button></div><div className="flex flex-col">{transactions.map(({ name, category, date, amount, tone, icon: Icon }) => <div key={name} className="flex items-center gap-3 border-t border-line py-4"><div className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${tone === 'income' ? 'bg-mint text-jade' : 'bg-paper text-muted'}`}><Icon size={17} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{name}</p><p className="mt-1 text-xs text-muted">{category} · {date}</p></div><p className={`text-sm font-bold ${tone === 'income' ? 'text-jade' : 'text-ink'}`}>{amount}</p></div>)}</div></section><section className="rounded-2xl border border-line bg-surface p-6 md:p-7"><div className="flex items-center justify-between"><div><h3 className="font-display text-xl font-bold">Objectifs</h3><p className="mt-1 text-sm text-muted">Vos projets en cours</p></div><Target size={20} className="text-jade" /></div><div className="mt-6 flex flex-col gap-6"><Goal name="Voyage au Sénégal" amount="420 000" percent={68} /><Goal name="Fonds de sécurité" amount="1 000 000" percent={34} /></div></section></div>
      </div></section>
  </main>
}
function StatCard({ label, value, delta, positive, icon: Icon }: { label: string; value: string; delta: string; positive?: boolean; icon: typeof ArrowDownLeft }) { return <div className="rounded-2xl border border-line bg-surface p-6"><div className="flex items-center justify-between"><p className="text-sm text-muted">{label}</p><Icon size={18} className={positive ? 'text-jade' : 'text-coral'} /></div><p className="mt-5 font-display text-3xl font-bold">{value} <span className="text-sm font-sans font-normal text-muted">FCFA</span></p><p className={`mt-3 text-xs font-bold ${positive ? 'text-jade' : 'text-coral'}`}>{delta} <span className="font-normal text-muted">ce mois</span></p></div> }
function Goal({ name, amount, percent }: { name: string; amount: string; percent: number }) { return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{name}</span><span className="font-bold text-jade">{percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-paper"><div className="h-full rounded-full bg-jade" style={{ width: `${percent}%` }} /></div><p className="mt-2 text-xs text-muted">{amount} FCFA économisés</p></div> }
